### ISSUE TITLE
where is the book file?

### ISSUE THREAD

**Issue by tissatussa** [justNo4b/Drofa#123]
in the UCI options i see Drofa can use an opening book .. where can we find it ?

**Comment by justNo4b** [comment]
Hello.
Currently there is no Drofa-specific opening book, and no plans for making one.
Drofa can use general polyglot-format opening books.
There are some of them on the internet, one example I was able to find is Perfect-2017 opening book provided by Sedat-chess:
https://sites.google.com/site/computerschess/perfect2017books
