### ISSUE TITLE
new engine Equisetum ?

### ISSUE THREAD

**Issue by tissatussa** [justNo4b/Drofa#226]
at page https://wiki.chessdom.org/TCEC_Swiss_5 i read :

_Drofa is "upgraded to new engine Equisetum"_

but nowhere i can find that engine, eg. at GitHub .. do you really work on "Equisetum" ?  Just curious ..

**Comment by tissatussa** [comment]
OK, in the TCEC chat i read :

_Equisetum is a private UCI-compatible chess engine by Alexander Litov (No4b) - it is the renamed upgrade of !Drofa and uses a NNUE trained on Drofa data. First TCEC appearance: S25 Swiss5._

**Comment by justNo4b** [comment]
Hello,
as it is stated in TCEC info, Equisetum is a private project.
Briefly, it uses current Drofa search combined with NNUE evaluation, trained with CUDAd trainer on Drofa data.

It will remain private for a while, no plans to release it in any way the near future.

Thank you for taking interest.
Best wishes,
No4b
