### ISSUE TITLE
Hash size problem

### ISSUE THREAD

**Issue by SzotsGabor** [justNo4b/Drofa#232]
Hello Alexander,

Please look at this: https://talkchess.com/forum3/viewtopic.php?f=2&t=83036&sid=7e138acfd814bd11eb6d93ceea2a3d32

I myself can confirm that Drofa uses about 1 GB under Fritz 17 when hash is set to 256 MB.

Regards,
Gabor Szots
CCRL testing group

**Comment by justNo4b** [comment]
Thank you for bringing this up to me.
I missed a bug during transposition table rewriting.

#233 and latest release 4.1.0_fixed release should fix that

**Comment by justNo4b** [comment]
#233
