### ISSUE TITLE
false positve

### ISSUE THREAD

**Issue by Vapenord** [justNo4b/Drofa#86]
Windows defender detects a trojan so severe that it physically stops me from allowing the download to happen, even from the windows defender dashboard. Obviously it's a false positive, is it possible to stop such a thing from happening?

**Comment by justNo4b** [comment]
Hello!
Thanks for pointing that out.
After some googling, I found out that this issue might be linked specifically with a *.zip archive and not a *.exe file.
At my PC, there is no warnings on *.exe, so I added executable to the 3.1.0 release.
Try to download it, hopefully it will work.

**Comment by Vapenord** [comment]
Works perfectly, thanks for the help. Wish you all the best with Drofa and everything else :)
